/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reel/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_reel_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/session/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Persona */
        post: operations["set_persona_api_reel_session_persona_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Genres */
        get: operations["genres_api_reel_genres_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tags
         * @description The most widely used community tags across the catalogue.
         */
        get: operations["tags_api_reel_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/films": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse */
        get: operations["browse_api_reel_films_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/films/{film_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Film */
        get: operations["film_api_reel_films__film_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Watch */
        post: operations["watch_api_reel_watch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/watch/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay
         * @description Re-send the shopper's last event with the SAME event_id: GraphRec must answer duplicate (NR-NF-05).
         */
        post: operations["replay_api_reel_watch_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_api_reel_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/feedback/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Click */
        post: operations["click_api_reel_feedback_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/insight/sequence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sequence */
        get: operations["sequence_api_reel_insight_sequence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/insight/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Every film in the shopper's history, most recent first, each film once (for "Recently watched" and ✓ marks).
         */
        get: operations["history_api_reel_insight_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reel/insight/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_reel_insight_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClickIn */
        ClickIn: {
            /** Requestid */
            requestId: string;
            /** Filmid */
            filmId: string;
            /** Position */
            position: number;
        };
        /** Diff */
        Diff: {
            /** Hasprevious */
            hasPrevious: boolean;
            /** Entered */
            entered: string[];
            /** Left */
            left: components["schemas"]["Film"][];
            /** Changed */
            changed: number;
            /** Summary */
            summary: string;
        };
        /** Envelope[FeedbackOut] */
        Envelope_FeedbackOut_: {
            data: components["schemas"]["FeedbackOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[FilmPage] */
        Envelope_FilmPage_: {
            data: components["schemas"]["FilmPage"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[Film] */
        Envelope_Film_: {
            data: components["schemas"]["Film"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[List[Film]] */
        Envelope_List_Film__: {
            /** Data */
            data: components["schemas"]["Film"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[List[Genre]] */
        Envelope_List_Genre__: {
            /** Data */
            data: components["schemas"]["Genre"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[List[Tag]] */
        Envelope_List_Tag__: {
            /** Data */
            data: components["schemas"]["Tag"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[Receipt] */
        Envelope_Receipt_: {
            data: components["schemas"]["Receipt"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[SequenceOut] */
        Envelope_SequenceOut_: {
            data: components["schemas"]["SequenceOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[SessionOut] */
        Envelope_SessionOut_: {
            data: components["schemas"]["SessionOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[StatusOut] */
        Envelope_StatusOut_: {
            data: components["schemas"]["StatusOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[Union[RecommendationsOut, Unavailable]] */
        Envelope_Union_RecommendationsOut__Unavailable__: {
            /** Data */
            data: components["schemas"]["RecommendationsOut"] | components["schemas"]["Unavailable"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Eventid */
            eventId: string;
            /** Accepted */
            accepted: boolean;
            /** Duplicate */
            duplicate: boolean;
        };
        /** Film */
        Film: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Genres */
            genres: string[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Popularity */
            popularity: number;
            /** Popularityrank */
            popularityRank: number;
            /** Tmdbid */
            tmdbId?: string | null;
            /** Imdbid */
            imdbId?: string | null;
            /** Posterurl */
            posterUrl?: string | null;
        };
        /** FilmPage */
        FilmPage: {
            /** Items */
            items: components["schemas"]["Film"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Genre */
        Genre: {
            /** Name */
            name: string;
            /** Films */
            films: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PersonaIn */
        PersonaIn: {
            /** Persona */
            persona: string;
            /**
             * Carrysession
             * @default false
             */
            carrySession: boolean;
        };
        /** PersonaOut */
        PersonaOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Blurb */
            blurb: string;
            /** Color */
            color: string;
            /** Userid */
            userId: string | null;
            /** Historylength */
            historyLength: number;
        };
        /** Ranked */
        Ranked: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Genres */
            genres: string[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Popularity */
            popularity: number;
            /** Popularityrank */
            popularityRank: number;
            /** Tmdbid */
            tmdbId?: string | null;
            /** Imdbid */
            imdbId?: string | null;
            /** Posterurl */
            posterUrl?: string | null;
            /** Position */
            position: number;
            /**
             * Change
             * @default same
             * @enum {string}
             */
            change: "new" | "up" | "down" | "same";
            /** Previousposition */
            previousPosition?: number | null;
        };
        /** Receipt */
        Receipt: {
            /** Eventid */
            eventId: string;
            /** Eventtype */
            eventType: string;
            /** Filmid */
            filmId: string;
            /** Accepted */
            accepted: boolean;
            /** Duplicate */
            duplicate: boolean;
            /** Latencyms */
            latencyMs: number;
            /** Feedback */
            feedback?: string | null;
        };
        /** RecommendationIn */
        RecommendationIn: {
            /**
             * Shelf
             * @default home
             * @enum {string}
             */
            shelf: "home" | "more_like";
            /** Filmid */
            filmId?: string | null;
        };
        /** RecommendationsOut */
        RecommendationsOut: {
            /**
             * Shelf
             * @enum {string}
             */
            shelf: "home" | "more_like";
            /** Title */
            title: string;
            /** Items */
            items: components["schemas"]["Ranked"][];
            trace: components["schemas"]["Trace"];
            diff: components["schemas"]["Diff"];
            /** Omitted */
            omitted: number;
            /** Impression */
            impression?: string | null;
        };
        /** SequenceItem */
        SequenceItem: {
            film: components["schemas"]["Film"];
            /** Time */
            time: number;
            /**
             * Origin
             * @enum {string}
             */
            origin: "training" | "live";
            /** Eventtype */
            eventType: string;
            /** Eventid */
            eventId?: string | null;
            /** Inwindow */
            inWindow: boolean;
            /**
             * Evicted
             * @default false
             */
            evicted: boolean;
        };
        /** SequenceOut */
        SequenceOut: {
            /** Shopper */
            shopper: string;
            /** Total */
            total: number;
            /** Window */
            window: number;
            /** Items */
            items: components["schemas"]["SequenceItem"][];
            /** Livecount */
            liveCount: number;
            /** Sessiononly */
            sessionOnly: boolean;
        };
        /** SessionOut */
        SessionOut: {
            persona: components["schemas"]["PersonaOut"];
            /** Sessionid */
            sessionId: string;
            /** Personas */
            personas: components["schemas"]["PersonaOut"][];
        };
        /** StatusOut */
        StatusOut: {
            /** Tenant */
            tenant: string;
            /** Graphrec */
            graphrec: string;
            /** Modelversionid */
            modelVersionId: string | null;
            /** Modelversiontag */
            modelVersionTag: string | null;
            /** Modelcard */
            modelCard: {
                [key: string]: unknown;
            } | null;
            /** Modelsource */
            modelSource: string;
            /** Liveevents */
            liveEvents: number;
            /** Feedbackhealth */
            feedbackHealth?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
            /** Readiness */
            readiness?: {
                [key: string]: string;
            } | null;
        };
        /** Tag */
        Tag: {
            /** Name */
            name: string;
            /** Films */
            films: number;
        };
        /** Trace */
        Trace: {
            request: components["schemas"]["TraceRequest"];
            /** Requestid */
            requestId: string;
            /** Modelversionid */
            modelVersionId: string | null;
            /** Strategy */
            strategy: string;
            /** Fallbackused */
            fallbackUsed: boolean;
            /** Fallbacktier */
            fallbackTier: string;
            /** Appliedrules */
            appliedRules: string[];
            /** Latencyms */
            latencyMs: number;
        };
        /** TraceRequest */
        TraceRequest: {
            /** Endpoint */
            endpoint: string;
            /** Userid */
            userId: string | null;
            /** Topn */
            topN: number;
            /** Recentproductids */
            recentProductIds: string[];
            /** Excludecount */
            excludeCount: number;
        };
        /** Unavailable */
        Unavailable: {
            /**
             * Available
             * @default false
             * @constant
             */
            available: false;
            /** Reason */
            reason: string;
            /** Correlationid */
            correlationId?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchIn */
        WatchIn: {
            /** Filmid */
            filmId: string;
            /** Requestid */
            requestId?: string | null;
            /** Position */
            position?: number | null;
            /**
             * Eventtype
             * @default rating
             * @enum {string}
             */
            eventType: "rating" | "purchase" | "view" | "click" | "add_to_wishlist";
            /** Rating */
            rating?: number | null;
            /**
             * Occurredat
             * @description Unix timestamp seconds
             */
            occurredAt?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_session_api_reel_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
        };
    };
    set_persona_api_reel_session_persona_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    genres_api_reel_genres_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_List_Genre__"];
                };
            };
        };
    };
    tags_api_reel_tags_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_List_Tag__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_api_reel_films_get: {
        parameters: {
            query?: {
                genre?: string | null;
                tag?: string | null;
                q?: string | null;
                sort?: "popular" | "newest" | "oldest" | "title";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FilmPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    film_api_reel_films__film_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                film_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Film_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_api_reel_watch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Receipt_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_api_reel_watch_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Receipt_"];
                };
            };
        };
    };
    recommend_api_reel_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_RecommendationsOut__Unavailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    click_api_reel_feedback_click_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClickIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FeedbackOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sequence_api_reel_insight_sequence_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SequenceOut_"];
                };
            };
        };
    };
    history_api_reel_insight_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_List_Film__"];
                };
            };
        };
    };
    status_api_reel_insight_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StatusOut_"];
                };
            };
        };
    };
}
