"""Shared vocabulary.

GENERATED by scripts/gen_enums.py from "Design system decision pending/GraphRec Console.dc.html".
Do not edit by hand. Run `python scripts/gen_enums.py` after changing the prototype.
"""

from __future__ import annotations

from enum import StrEnum


class JobState(StrEnum):
    """Training job state (12 values). Drives the job badge."""

    QUEUED = "queued"
    WAITING_FOR_RESOURCES = "waiting_for_resources"
    PREPARING_DATA = "preparing_data"
    BUILDING_GRAPH = "building_graph"
    TRAINING = "training"
    EVALUATING = "evaluating"
    INDEXING_EMBEDDINGS = "indexing_embeddings"
    REGISTERING = "registering"
    CANCELLING = "cancelling"
    CANCELLED = "cancelled"
    FAILED = "failed"
    SUCCEEDED = "succeeded"


class ModelVersionStatus(StrEnum):
    """Model version lifecycle (7 values) — D8."""

    REGISTERED = "registered"
    ARCHIVED = "archived"
    ELIGIBLE = "eligible"
    RETIRED = "retired"
    REJECTED = "rejected"
    FAILED_DEPLOYMENT = "failed_deployment"
    ACTIVE = "active"


class DeploymentState(StrEnum):
    """Deployment state (6 values)."""

    STOPPED = "stopped"
    PENDING = "pending"
    PROGRESSING = "progressing"
    DEGRADED = "degraded"
    ROLLING_BACK = "rolling_back"
    AVAILABLE = "available"


class TenantStatus(StrEnum):
    """Tenant account status (5 values)."""

    DELETED = "deleted"
    PENDING = "pending"
    SUSPENDED = "suspended"
    DELETING = "deleting"
    ACTIVE = "active"


class UserStatus(StrEnum):
    """Tenant user status (4 values)."""

    INVITED = "invited"
    LOCKED = "locked"
    DISABLED = "disabled"
    ACTIVE = "active"


class AuditOutcome(StrEnum):
    """Audit outcome (4 values)."""

    CANCELLED = "cancelled"
    DENIED = "denied"
    FAILED = "failed"
    SUCCEEDED = "succeeded"


class Severity(StrEnum):
    """Failure severity (4 values)."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class Credential(StrEnum):
    """credential vocabulary."""

    USABLE = "usable"
    EXPIRED = "expired"
    REVOKED = "revoked"


class Submission(StrEnum):
    """submission vocabulary."""

    PROCESSING = "processing"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class Availability(StrEnum):
    """From seed() products[].avail."""

    IN_STOCK = "in_stock"
    LOW_STOCK = "low_stock"
    OUT_OF_STOCK = "out_of_stock"


class EventType(StrEnum):
    """From /integration event shape; seed() audit and usage rows."""

    VIEW = "view"
    ADD_TO_CART = "add_to_cart"
    PURCHASE = "purchase"
    REMOVE_FROM_CART = "remove_from_cart"


class SubmissionKind(StrEnum):
    """From seed() submissions[].kind."""

    PRODUCT_SYNC = "product_sync"
    EVENT_BATCH = "event_batch"


class SubmissionStatus(StrEnum):
    """From BACKEND_PLAN §12 submission lifecycle; console renders 'processing'."""

    RECEIVED = "received"
    VALIDATING = "validating"
    APPLYING = "applying"
    COMPLETED = "completed"
    FAILED = "failed"


class UsageType(StrEnum):
    """From seed() usage[].type."""

    EVENTS = "events"
    RECOMMENDATIONS = "recommendations"
    TRAINING = "training"
    PRODUCTS = "products"
    STORAGE = "storage"
    SERVICE_CAPACITY = "service_capacity"


class MeasurementStatus(StrEnum):
    """From seed() usage[].status and qty:'unavailable' (L715)."""

    MEASURED = "measured"
    DELAYED = "delayed"
    UNAVAILABLE = "unavailable"


class AuditActor(StrEnum):
    """From seed() audit[].actor."""

    TENANT_USER = "tenant_user"
    TENANT_APPLICATION = "tenant_application"
    SYSTEM_PROCESS = "system_process"
    PLATFORM_ADMINISTRATOR = "platform_administrator"


class AuditAction(StrEnum):
    """From seed() audit[].action."""

    CREDENTIAL = "credential"
    TRAINING = "training"
    ACTIVATION = "activation"
    ROLLBACK = "rollback"
    QUOTA = "quota"
    TENANT = "tenant"
    ACCESS = "access"
    SECURITY = "security"


class FailureArea(StrEnum):
    """From seed() failures[].area."""

    SERVING = "serving"
    INGESTION = "ingestion"
    TRAINING = "training"
    ACTIVATION = "activation"
    CAPACITY = "capacity"


class CredentialState(StrEnum):
    """From derived predicate at L1107 — server time is authoritative."""

    USABLE = "usable"
    EXPIRED = "expired"
    REVOKED = "revoked"


class TenantRole(StrEnum):
    """From const ADMIN / DEV (L636)."""

    TENANT_ADMINISTRATOR = "tenant_administrator"
    TENANT_DEVELOPER = "tenant_developer"


class CredentialScope(StrEnum):
    """Credential scopes. The wire carries these; the console shows SCOPE_LABELS."""

    CATALOG_WRITE = "catalog:write"
    EVENTS_WRITE = "events:write"
    RECOMMENDATIONS_READ = "recommendations:read"
    FEEDBACK_WRITE = "feedback:write"
    SUBMISSIONS_READ = "submissions:read"


class PlatformPermission(StrEnum):
    """The five independently grantable platform permissions."""

    PLATFORM = "platform"
    PLAN_MANAGEMENT = "plan_management"
    PLATFORM_SCOPE = "platform_scope"
    MONITORING = "monitoring"
    AUDIT = "audit"


#: Ordered training stages — drives the console's stage rail.
JOB_STAGES: tuple[JobState, ...] = (
    JobState.QUEUED,
    JobState.WAITING_FOR_RESOURCES,
    JobState.PREPARING_DATA,
    JobState.BUILDING_GRAPH,
    JobState.TRAINING,
    JobState.EVALUATING,
    JobState.INDEXING_EMBEDDINGS,
    JobState.REGISTERING,
    JobState.SUCCEEDED,
)


#: Badge tone per value, per group. The console renders these; an
#: unknown value falls back to an untoned badge.
BADGE_TONES: dict[str, dict[str, str]] = {
    "job": {
        "queued": "neu",
        "waiting_for_resources": "neu",
        "preparing_data": "info",
        "building_graph": "info",
        "training": "info",
        "evaluating": "info",
        "indexing_embeddings": "info",
        "registering": "info",
        "cancelling": "warn",
        "cancelled": "warn",
        "failed": "danger",
        "succeeded": "ok",
    },
    "model": {
        "registered": "neu",
        "archived": "neu",
        "eligible": "info",
        "retired": "warn",
        "rejected": "warn",
        "failed_deployment": "danger",
        "active": "ok",
    },
    "deploy": {
        "stopped": "neu",
        "pending": "info",
        "progressing": "info",
        "degraded": "warn",
        "rolling_back": "warn",
        "available": "ok",
    },
    "tenant": {
        "deleted": "neu",
        "pending": "info",
        "suspended": "warn",
        "deleting": "warn",
        "active": "ok",
    },
    "user": {
        "invited": "info",
        "locked": "warn",
        "disabled": "danger",
        "active": "ok",
    },
    "outcome": {
        "cancelled": "neu",
        "denied": "warn",
        "failed": "danger",
        "succeeded": "ok",
    },
    "sev": {
        "info": "info",
        "warning": "warn",
        "error": "danger",
        "critical": "danger",
    },
    "credential": {
        "usable": "ok",
        "expired": "warn",
        "revoked": "danger",
    },
    "submission": {
        "processing": "info",
        "succeeded": "ok",
        "failed": "danger",
    },
}


#: Machine name -> the label the console displays.
SCOPE_LABELS: dict[CredentialScope, str] = {
    CredentialScope.CATALOG_WRITE: "catalog write & synchronization",
    CredentialScope.EVENTS_WRITE: "event submission (single and batch)",
    CredentialScope.RECOMMENDATIONS_READ: "recommendation requests",
    CredentialScope.FEEDBACK_WRITE: "recommendation feedback",
    CredentialScope.SUBMISSIONS_READ: "submission result read",
}

#: Machine name -> the abbreviated label used in table columns.
SCOPE_SHORT_LABELS: dict[CredentialScope, str] = {
    CredentialScope.CATALOG_WRITE: "catalog write",
    CredentialScope.EVENTS_WRITE: "event submission",
    CredentialScope.RECOMMENDATIONS_READ: "recommendations",
    CredentialScope.FEEDBACK_WRITE: "feedback",
    CredentialScope.SUBMISSIONS_READ: "result read",
}

PERMISSION_LABELS: dict[PlatformPermission, str] = {
    PlatformPermission.PLATFORM: "platform permission",
    PlatformPermission.PLAN_MANAGEMENT: "plan-management permission",
    PlatformPermission.PLATFORM_SCOPE: "authorized platform scope",
    PlatformPermission.MONITORING: "monitoring access",
    PlatformPermission.AUDIT: "audit permission",
}

SUBMISSION_KIND_LABELS: dict[SubmissionKind, str] = {
    SubmissionKind.PRODUCT_SYNC: "product sync",
    SubmissionKind.EVENT_BATCH: "event batch",
}

MEASUREMENT_STATUS_LABELS: dict[MeasurementStatus, str] = {
    MeasurementStatus.MEASURED: "measured",
    MeasurementStatus.DELAYED: "measurement delayed",
    MeasurementStatus.UNAVAILABLE: "unavailable",
}

TENANT_ROLE_LABELS: dict[TenantRole, str] = {
    TenantRole.TENANT_ADMINISTRATOR: "tenant administrator",
    TenantRole.TENANT_DEVELOPER: "tenant developer",
}
