"""The runbooks, checked against the platform they describe.

A runbook is read once, at 03:00, by someone who cannot verify it. Every minute
spent discovering that a documented command does not exist is a minute of the
incident, so the parts of `docs/RUNBOOKS.md` that *can* be checked mechanically
are checked here.

Three of them can:

* every `$API/v1/...` call it tells an operator to make is a route this server
  serves, with the method it says — the same contract check
  `frontend/src/api/contract.test.ts` applies to the console, applied to the
  documentation;
* every SQL table it tells an operator to query is a table that exists;
* every internal cross-reference resolves to a heading in the same file.

Writing this found two wrong paths in the first draft: a `:cancel` route for
jobs in general, which does not exist and never has (only training jobs have
one), and `/v1/models/{model_id}/deployments`, which was invented from the
shape of the rollback route. Both would have been discovered by an operator,
mid-incident, with no way to find the right one.

What it cannot check is whether the advice is correct. That is what the
rehearsed drill is for on the restore path, and reading is for on the rest.
"""

from __future__ import annotations

import json
import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
RUNBOOKS = ROOT / "docs" / "RUNBOOKS.md"
OPENAPI = ROOT / "frontend" / "openapi.json"

#: `$API/v1/foo/{bar}:baz`, in prose or in a curl line, quoted or backticked.
CALL = re.compile(r"\$API(/v1/[A-Za-z0-9_\-{}/:.]*)")

#: The method sits before the path and not always adjacently — `curl -X POST
#: "$API/..."` and "`POST $API/...`" and "`GET\n   $API/...`" all occur.
_VERBS = "GET|POST|PATCH|PUT|DELETE"
METHOD_BEFORE = re.compile(rf"\b({_VERBS})\b(?![\s\S]*?\b(?:{_VERBS})\b)")


@pytest.fixture(scope="module")
def text() -> str:
    return RUNBOOKS.read_text()


@pytest.fixture(scope="module")
def document() -> dict:
    if not OPENAPI.exists():  # pragma: no cover - generated by scripts/gen_openapi.py
        pytest.skip("frontend/openapi.json has not been generated")
    return json.loads(OPENAPI.read_text())


def _calls(text: str) -> list[tuple[str, str]]:
    """(method, path) for every documented API call, method inferred backwards.

    Backwards because that is how they are written: the verb comes first, and
    sometimes a line break comes between it and the URL.
    """
    found: list[tuple[str, str]] = []
    for match in CALL.finditer(text):
        preceding = text[max(0, match.start() - 120) : match.start()]
        verb = METHOD_BEFORE.search(preceding)
        found.append((verb.group(1) if verb else "GET", match.group(1).rstrip(".,`\"'")))
    return found


def test_it_finds_the_calls_it_is_supposed_to_be_checking(text) -> None:
    """The floor. A regex that matches nothing passes every test below.

    Same reason `contract.test.ts` has one: a rename that made this scanner
    blind would turn the whole file into a test that cannot fail.
    """
    calls = _calls(text)
    assert len(calls) >= 5, calls
    paths = {path for _, path in calls}
    assert "/v1/models/{model_id}:rollback" in paths
    assert "/v1/platform/tenants/{tenant_id}:status" in paths


def test_every_documented_call_is_a_route_the_server_serves(text, document) -> None:
    served = set(document["paths"])
    missing = sorted({path for _, path in _calls(text) if path not in served})
    assert not missing, f"RUNBOOKS.md tells an operator to call paths that do not exist: {missing}"


def test_every_documented_call_uses_a_method_that_route_accepts(text, document) -> None:
    wrong = [
        (method, path)
        for method, path in _calls(text)
        if path in document["paths"] and method.lower() not in document["paths"][path]
    ]
    assert not wrong, f"RUNBOOKS.md documents methods these routes do not accept: {wrong}"


def test_every_table_it_tells_you_to_query_exists(text) -> None:
    """The SQL in here is read-only and diagnostic, and a `FROM` on a table that
    was renamed three migrations ago fails at exactly the wrong moment."""
    from graphrec.db.models.base import Base

    known = set(Base.metadata.tables)
    referenced = {
        name
        for name in re.findall(r"\bFROM\s+([a-z_][a-z0-9_]*)", text)
        if not name.startswith("pg_")
    }
    assert referenced, "no SQL found in the runbooks at all"
    missing = sorted(referenced - known)
    assert not missing, f"RUNBOOKS.md queries tables that do not exist: {missing}"


def test_every_cross_reference_resolves(text) -> None:
    """`[force a rollback](#force-a-rollback)` from six sections. One rename
    breaks all six, silently, because Markdown does not check links."""
    headings = {
        re.sub(r"[^a-z0-9]+", "-", line.lstrip("#").strip().lower()).strip("-")
        for line in text.splitlines()
        if line.startswith("#")
    }
    links = set(re.findall(r"\]\(#([a-z0-9-]+)\)", text))
    assert links, "the runbooks cross-reference nothing"
    assert not sorted(links - headings), f"dead internal links: {sorted(links - headings)}"


def test_every_alert_has_a_section_and_every_section_an_alert() -> None:
    """Both directions. An alert with no runbook is the failure
    `test_alert_rules.py` catches; a runbook section no alert points at is a
    procedure nobody will find, which is the same waste in the other direction.

    The `## Procedures` half is exempt: those are written down because §24 asks
    for them, not because something fires.
    """
    import yaml

    rules = yaml.safe_load((ROOT / "deploy" / "observability" / "alerts.yml").read_text())
    linked = {
        rule["annotations"]["runbook"].split("#", 1)[1]
        for group in rules["groups"]
        for rule in group["rules"]
    }

    lines = RUNBOOKS.read_text().splitlines()
    incidents = lines.index("## Incidents")
    procedures = lines.index("## Procedures")
    sections = {
        re.sub(r"[^a-z0-9]+", "-", line[4:].strip().lower()).strip("-")
        for line in lines[incidents:procedures]
        if line.startswith("### ")
    }
    assert sections == linked, f"unlinked: {sections - linked}, unwritten: {linked - sections}"
