"""GraphRec Python SDK.

Typed, retrying clients for every GraphRec API: catalog sync, customer events,
recommendations and feedback for storefronts, plus tenant administration
(API keys, datasets, training, model versions, usage) and platform operations.
"""

from . import ecommerce, models
from ._auth import ApiKeyAuth, Auth, BearerTokenAuth, PasswordAuth
from ._client import AsyncGraphRec, GraphRec
from ._ids import deterministic_id, new_id
from ._retry import RetryPolicy
from ._routes import ROUTES, Route
from ._version import __version__
from .enums import (
    ApiKeyStatus,
    AvailabilityStatus,
    EventType,
    FallbackTier,
    FeedbackType,
    ModelStatus,
    PlanCode,
    RecommendationStrategy,
    TenantStatus,
    TrainingStatus,
    UsageType,
    UserRole,
)
from .errors import (
    APIConnectionError,
    APIError,
    APIResponseValidationError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    ConfigurationError,
    ConflictError,
    DuplicateResourceError,
    FieldError,
    GraphRecError,
    IdempotencyConflictError,
    InputValidationError,
    InternalServerError,
    MalformedRequestError,
    NotFoundError,
    PayloadTooLargeError,
    PermissionDeniedError,
    QuotaExceededError,
    RateLimitError,
    RequestValidationError,
    ServiceUnavailableError,
    StateConflictError,
    TokenExpiredError,
    WaitTimeoutError,
)
from .models import EventInput, ProductInput
from .scopes import (
    API_KEY_SCOPES,
    CATALOG_SYNC_KEY_SCOPES,
    DELEGATABLE_SCOPES,
    ROLE_SCOPES,
    STOREFRONT_KEY_SCOPES,
    Scope,
)

__all__ = [
    "API_KEY_SCOPES",
    "CATALOG_SYNC_KEY_SCOPES",
    "DELEGATABLE_SCOPES",
    "ROLE_SCOPES",
    "ROUTES",
    "STOREFRONT_KEY_SCOPES",
    "APIConnectionError",
    "APIError",
    "APIResponseValidationError",
    "APIStatusError",
    "APITimeoutError",
    "ApiKeyAuth",
    "ApiKeyStatus",
    "AsyncGraphRec",
    "Auth",
    "AuthenticationError",
    "AvailabilityStatus",
    "BearerTokenAuth",
    "ConfigurationError",
    "ConflictError",
    "DuplicateResourceError",
    "EventInput",
    "EventType",
    "FallbackTier",
    "FeedbackType",
    "FieldError",
    "GraphRec",
    "GraphRecError",
    "IdempotencyConflictError",
    "InputValidationError",
    "InternalServerError",
    "MalformedRequestError",
    "ModelStatus",
    "NotFoundError",
    "PasswordAuth",
    "PayloadTooLargeError",
    "PermissionDeniedError",
    "PlanCode",
    "ProductInput",
    "QuotaExceededError",
    "RateLimitError",
    "RecommendationStrategy",
    "RequestValidationError",
    "RetryPolicy",
    "Route",
    "Scope",
    "ServiceUnavailableError",
    "StateConflictError",
    "TenantStatus",
    "TokenExpiredError",
    "TrainingStatus",
    "UsageType",
    "UserRole",
    "WaitTimeoutError",
    "__version__",
    "deterministic_id",
    "ecommerce",
    "models",
    "new_id",
]
