import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

test('model replacement, rollback and archive follow confirmed backend state', async ({ page, request }) => {
  const tag = Date.now().toString(36);
  const email = `lifecycle-${tag}@example.org`;
  const password = `Lifecycle-${tag}-password`;
  const admin = readFileSync(resolve('..', '.env'), 'utf8').split(/\r?\n/).find(line => line.startsWith('PLATFORM_ADMIN_TOKEN='))?.slice(21).trim();
  expect(admin).toBeTruthy();
  const api = async (path: string, data?: unknown, token?: string, method = data ? 'POST' : 'GET') => {
    const response = await request.fetch(`/v1${path}`, { method, data, headers: { Accept: 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(path === '/tenants' ? { 'Idempotency-Key': tag } : {}) } });
    expect(response.ok(), `${method} ${path}: ${response.status()}`).toBeTruthy();
    return response.json();
  };
  const tenant = await api('/tenants', { name: `Lifecycle test ${tag}`, admin_email: email });
  const auth = await api('/auth/setup-password', { setup_token: tenant.setup_token, password, email });
  const token = auth.access_token;
  await api(`/platform/tenants/${tenant.id}/quotas`, { overrides: { training_jobs: 2 } }, admin);
  await api('/products/LIFECYCLE-1', { external_id: 'LIFECYCLE-1', title: 'Lifecycle test product', price: '10.00' }, token, 'PUT');
  await api('/events', { event_id: `event-${tag}`, event_type: 'purchase', user_id: 'test-user', external_product_id: 'LIFECYCLE-1' }, token);
  const first = await api('/training-jobs', { configuration: { mode: 'placeholder' } }, token);
  const second = await api('/training-jobs', { configuration: { mode: 'placeholder' } }, token);
  await api(`/model-versions/${first.model_version_id}:activate`, {}, token);
  await page.goto('/login');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/home$/);
  await page.goto(`/models/${second.model_version_id}`);
  await page.getByRole('button', { name: 'Activate', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: /^Activate / }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect(page.locator('.page-header .tag')).toHaveText('active');
  expect((await api('/deployment', undefined, token)).active_model_version_id).toBe(second.model_version_id);
  await page.getByRole('button', { name: 'Roll back', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Roll-back target').selectOption(first.model_version_id);
  await page.getByRole('dialog').getByRole('button', { name: 'Roll back', exact: true }).click();
  await expect(page).toHaveURL(/\/models$/);
  expect((await api('/deployment', undefined, token)).active_model_version_id).toBe(first.model_version_id);
  await page.goto(`/models/${second.model_version_id}`);
  await page.getByRole('button', { name: 'Archive', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(page).toHaveURL(/\/models$/);
  expect((await api(`/model-versions/${second.model_version_id}`, undefined, token)).status).toBe('archived');
  await page.goto(`/models/${second.model_version_id}`);
  await expect(page.locator('.page-header .tag')).toHaveText('archived');
  await expect(page.getByRole('button', { name: 'Activate', exact: true })).toHaveCount(0);
});
