#!/usr/bin/env python3
"""Generate the shared vocabulary from the console prototype.

The prototype is the specification (BUILD_PROMPT §0). Its `GROUPS`, `JOB_STAGES`,
`SCOPES`, `SCOPE_SHORT` and `PERMS` constants are the badge vocabulary: a value
the backend emits outside these sets renders as an untoned badge. So the
vocabulary is *parsed from* the prototype rather than transcribed, and the same
parse feeds both the Python enums and the TypeScript unions. A drift between them
cannot survive a build.

Two kinds of vocabulary exist here:

* **Parsed** — read out of the prototype's constants. Authoritative.
* **Declared** — vocabularies the prototype only expresses through its seed data
  (availability, event types, usage types, ...). These are declared below, but
  the generator *verifies every declared value literally appears in the
  prototype*, so deleting or renaming one there still fails this script.

Usage:
    python scripts/gen_enums.py            # write the generated files
    python scripts/gen_enums.py --check    # fail if they are stale (CI)
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROTOTYPE = ROOT / "Design system decision pending" / "GraphRec Console.dc.html"
PYTHON_OUT = ROOT / "graphrec" / "common" / "enums.py"
TYPESCRIPT_OUT = ROOT / "frontend" / "src" / "lib" / "enums.ts"

BANNER = (
    "GENERATED by scripts/gen_enums.py from "
    '"Design system decision pending/GraphRec Console.dc.html".\n'
    "Do not edit by hand. Run `python scripts/gen_enums.py` after changing the prototype."
)


# --------------------------------------------------------------------------- parsing


def _read_prototype() -> str:
    if not PROTOTYPE.exists():
        sys.exit(f"prototype not found: {PROTOTYPE}")
    return PROTOTYPE.read_text(encoding="utf-8")


def _js_string_list(source: str, name: str) -> list[str]:
    """Extract `const NAME=['a','b',...]`."""
    match = re.search(rf"const\s+{name}\s*=\s*\[(.*?)\]\s*;", source, re.DOTALL)
    if not match:
        sys.exit(f"could not find `const {name}=[...]` in the prototype")
    return re.findall(r"'([^']*)'", match.group(1))


def _js_string_map(source: str, name: str) -> dict[str, str]:
    """Extract `const NAME={'a':'b',...}`."""
    match = re.search(rf"const\s+{name}\s*=\s*\{{(.*?)\}}\s*;", source, re.DOTALL)
    if not match:
        sys.exit(f"could not find `const {name}={{...}}` in the prototype")
    return dict(re.findall(r"'([^']*)'\s*:\s*'([^']*)'", match.group(1)))


#: Badge tones for vocabularies the prototype never badged.
#:
#: `GROUPS` in the prototype carries a tone per value for the seven things it
#: drew a badge for. Two more became badge-worthy once the console was wired to
#: a real API: a credential's server-derived `state` (BUILD_PROMPT §10.9's sixth
#: console-only field — the prototype computed `expires < today` client-side and
#: rendered it as text) and a submission's `status`, which the prototype only
#: ever showed mid-flight.
#:
#: They are declared here rather than written into `Badge` because §10.5's rule
#: is that a badge's tone is looked up in the generated map and never
#: hard-coded per value. That rule is about where the mapping lives, not about
#: which file the prototype happened to put it in — so the mapping stays
#: generated, stays in one place, and stays pinned by
#: `tests/contract/test_enum_parity.py`.
DECLARED_TONES: dict[str, dict[str, str]] = {
    "credential": {"usable": "ok", "expired": "warn", "revoked": "danger"},
    "submission": {"processing": "info", "succeeded": "ok", "failed": "danger"},
}


def _parse_groups(source: str) -> dict[str, dict[str, str]]:
    """Extract `const GROUPS={ job:{queued:'neu',...}, ... }` as group -> value -> tone."""
    match = re.search(r"const\s+GROUPS\s*=\s*\{(.*?)\n\}\s*;", source, re.DOTALL)
    if not match:
        sys.exit("could not find `const GROUPS={...}` in the prototype")

    groups: dict[str, dict[str, str]] = {}
    for group_name, body in re.findall(r"(\w+)\s*:\s*\{([^}]*)\}", match.group(1)):
        entries = re.findall(r"(\w+)\s*:\s*'(\w+)'", body)
        if entries:
            groups[group_name] = dict(entries)
    groups.pop("plain", None)  # a renderer escape hatch, not a vocabulary
    groups.update(DECLARED_TONES)
    return groups


# --------------------------------------------------------------------------- declared


@dataclass(frozen=True)
class Declared:
    """A vocabulary the prototype expresses only through seed data or a predicate.

    `values` are the wire values. `labels` maps a wire value to the string the
    prototype renders, where the two differ — the wire carries a stable machine
    name and the console shows the human label, exactly as SCOPES already does.
    `verify` are literals that must be present in the prototype for this
    vocabulary to still be accurate.
    """

    name: str
    values: tuple[str, ...]
    source: str
    labels: dict[str, str] = field(default_factory=dict)
    verify: tuple[str, ...] = ()

    def verification_literals(self) -> tuple[str, ...]:
        return self.verify or tuple(self.labels.get(v, v) for v in self.values)


DECLARED: tuple[Declared, ...] = (
    Declared(
        name="availability",
        values=("in_stock", "low_stock", "out_of_stock"),
        source="seed() products[].avail",
    ),
    Declared(
        name="event_type",
        values=("view", "add_to_cart", "purchase", "remove_from_cart"),
        source="/integration event shape; seed() audit and usage rows",
    ),
    Declared(
        name="submission_kind",
        values=("product_sync", "event_batch"),
        source="seed() submissions[].kind",
        # The console renders these with a space; the wire carries snake_case.
        labels={"product_sync": "product sync", "event_batch": "event batch"},
    ),
    Declared(
        name="submission_status",
        values=("received", "validating", "applying", "completed", "failed"),
        source="BACKEND_PLAN §12 submission lifecycle; console renders 'processing'",
        # The console collapses the three in-flight states to one badge.
        verify=("processing", "succeeded", "failed"),
    ),
    Declared(
        name="usage_type",
        values=(
            "events",
            "recommendations",
            "training",
            "products",
            "storage",
            "service_capacity",
        ),
        source="seed() usage[].type",
    ),
    Declared(
        name="measurement_status",
        values=("measured", "delayed", "unavailable"),
        source="seed() usage[].status and qty:'unavailable' (L715)",
        labels={"delayed": "measurement delayed"},
    ),
    Declared(
        name="audit_actor",
        values=(
            "tenant_user",
            "tenant_application",
            "system_process",
            "platform_administrator",
        ),
        source="seed() audit[].actor",
    ),
    Declared(
        name="audit_action",
        values=(
            "credential",
            "training",
            "activation",
            "rollback",
            "quota",
            "tenant",
            "access",
            "security",
        ),
        source="seed() audit[].action",
    ),
    Declared(
        name="failure_area",
        values=("serving", "ingestion", "training", "activation", "capacity"),
        source="seed() failures[].area",
    ),
    Declared(
        name="credential_state",
        values=("usable", "expired", "revoked"),
        source="derived predicate at L1107 — server time is authoritative",
    ),
    Declared(
        name="tenant_role",
        values=("tenant_administrator", "tenant_developer"),
        source="const ADMIN / DEV (L636)",
        labels={
            "tenant_administrator": "tenant administrator",
            "tenant_developer": "tenant developer",
        },
    ),
)


#: Machine names for the five credential scopes. The prototype's SCOPES are
#: human labels; the wire needs stable identifiers (BUILD_PROMPT §6).
SCOPE_MACHINE_NAMES: dict[str, str] = {
    "catalog write & synchronization": "catalog:write",
    "event submission (single and batch)": "events:write",
    "recommendation requests": "recommendations:read",
    "recommendation feedback": "feedback:write",
    "submission result read": "submissions:read",
}

#: Vocabularies fixed by a confirmed decision rather than free to drift.
#:
#: The parsed constants above are whatever the prototype says, so renaming a
#: value there would otherwise regenerate cleanly and break the backend only at
#: import time. These sets pin the decisions: D8 fixes the model lifecycle at
#: seven values, the stage rail at nine, and BUILD_PROMPT §6 fixes the rest. A
#: change here is a decision to be confirmed, not a regeneration.
LOCKED_VOCABULARIES: dict[str, frozenset[str]] = {
    "GROUPS.job": frozenset(
        {
            "queued",
            "waiting_for_resources",
            "preparing_data",
            "building_graph",
            "training",
            "evaluating",
            "indexing_embeddings",
            "registering",
            "cancelling",
            "cancelled",
            "failed",
            "succeeded",
        }
    ),
    # D8 — the seven the console tones. TRAINING/EVALUATED/FAILED stay inside
    # the training job; DEPLOYING is model_deployments.state = 'progressing'.
    "GROUPS.model": frozenset(
        {
            "registered",
            "eligible",
            "active",
            "retired",
            "rejected",
            "archived",
            "failed_deployment",
        }
    ),
    "GROUPS.deploy": frozenset(
        {"stopped", "pending", "progressing", "degraded", "rolling_back", "available"}
    ),
    "GROUPS.tenant": frozenset({"pending", "active", "suspended", "deleting", "deleted"}),
    "GROUPS.user": frozenset({"invited", "active", "locked", "disabled"}),
    "GROUPS.outcome": frozenset({"succeeded", "failed", "denied", "cancelled"}),
    "GROUPS.sev": frozenset({"info", "warning", "error", "critical"}),
}

#: The stage rail is ordered, so it is pinned as a sequence, not a set.
LOCKED_JOB_STAGES: tuple[str, ...] = (
    "queued",
    "waiting_for_resources",
    "preparing_data",
    "building_graph",
    "training",
    "evaluating",
    "indexing_embeddings",
    "registering",
    "succeeded",
)

#: Machine names for the five platform permissions.
PERM_MACHINE_NAMES: dict[str, str] = {
    "platform permission": "platform",
    "plan-management permission": "plan_management",
    "authorized platform scope": "platform_scope",
    "monitoring access": "monitoring",
    "audit permission": "audit",
}


# --------------------------------------------------------------------------- model


@dataclass
class Vocabulary:
    groups: dict[str, dict[str, str]]
    job_stages: list[str]
    scopes: list[str]
    scope_short: dict[str, str]
    perms: list[str]


def load_vocabulary() -> Vocabulary:
    source = _read_prototype()
    vocab = Vocabulary(
        groups=_parse_groups(source),
        job_stages=_js_string_list(source, "JOB_STAGES"),
        scopes=_js_string_list(source, "SCOPES"),
        scope_short=_js_string_map(source, "SCOPE_SHORT"),
        perms=_js_string_list(source, "PERMS"),
    )

    problems: list[str] = []

    # A locked vocabulary changed means a decision changed. Say so loudly rather
    # than regenerating past it.
    for key, expected in LOCKED_VOCABULARIES.items():
        group = key.split(".", 1)[1]
        actual = frozenset(vocab.groups.get(group, {}))
        if actual != expected:
            added = sorted(actual - expected)
            removed = sorted(expected - actual)
            detail = ", ".join(
                part
                for part in (
                    f"added {added}" if added else "",
                    f"removed {removed}" if removed else "",
                )
                if part
            )
            problems.append(
                f"{key} is locked by a confirmed decision ({len(expected)} values) "
                f"but the prototype now differs: {detail}. "
                "Confirm the decision change, update LOCKED_VOCABULARIES, then regenerate"
            )

    if tuple(vocab.job_stages) != LOCKED_JOB_STAGES:
        problems.append(
            f"JOB_STAGES is locked as an ordered rail of {len(LOCKED_JOB_STAGES)} stages "
            f"{LOCKED_JOB_STAGES} but the prototype now has {tuple(vocab.job_stages)}"
        )

    # Every declared value must still be traceable to the prototype.
    for declared in DECLARED:
        for literal in declared.verification_literals():
            if f"'{literal}'" not in source:
                problems.append(
                    f"declared vocabulary {declared.name!r} expects {literal!r} "
                    f"in the prototype ({declared.source}), but it is absent"
                )

    # Machine-name maps must cover exactly the parsed label sets.
    for label in vocab.scopes:
        if label not in SCOPE_MACHINE_NAMES:
            problems.append(f"scope {label!r} has no machine name in SCOPE_MACHINE_NAMES")
    for label in vocab.perms:
        if label not in PERM_MACHINE_NAMES:
            problems.append(f"permission {label!r} has no machine name in PERM_MACHINE_NAMES")
    for label in SCOPE_MACHINE_NAMES:
        if label not in vocab.scopes:
            problems.append(f"SCOPE_MACHINE_NAMES has {label!r}, absent from the prototype")
    for label in PERM_MACHINE_NAMES:
        if label not in vocab.perms:
            problems.append(f"PERM_MACHINE_NAMES has {label!r}, absent from the prototype")

    # Every job stage must be a value in the job badge group.
    for stage in vocab.job_stages:
        if stage not in vocab.groups.get("job", {}):
            problems.append(f"JOB_STAGES has {stage!r}, absent from GROUPS.job")

    if problems:
        sys.exit("the prototype and this generator disagree:\n  - " + "\n  - ".join(problems))
    return vocab


# --------------------------------------------------------------------------- emit


def _py_enum(class_name: str, values: list[str], doc: str) -> str:
    lines = [f"class {class_name}(StrEnum):", f'    """{doc}"""', ""]
    for value in values:
        member = re.sub(r"\W", "_", value).upper()
        if member[0].isdigit():
            member = f"V_{member}"
        lines.append(f'    {member} = "{value}"')
    return "\n".join(lines)


def render_python(vocab: Vocabulary) -> str:
    out: list[str] = [
        '"""Shared vocabulary.',
        "",
        BANNER,
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
        "",
    ]

    group_docs = {
        "job": "Training job state (12 values). Drives the job badge.",
        "model": "Model version lifecycle (7 values) — D8.",
        "deploy": "Deployment state (6 values).",
        "tenant": "Tenant account status (5 values).",
        "user": "Tenant user status (4 values).",
        "outcome": "Audit outcome (4 values).",
        "sev": "Failure severity (4 values).",
    }
    class_names = {
        "job": "JobState",
        "model": "ModelVersionStatus",
        "deploy": "DeploymentState",
        "tenant": "TenantStatus",
        "user": "UserStatus",
        "outcome": "AuditOutcome",
        "sev": "Severity",
    }

    for group, tones in vocab.groups.items():
        out.append(
            _py_enum(
                class_names.get(group, group.title()),
                list(tones),
                group_docs.get(group, f"{group} vocabulary."),
            )
        )
        out.append("\n")

    for declared in DECLARED:
        class_name = "".join(part.title() for part in declared.name.split("_"))
        out.append(_py_enum(class_name, list(declared.values), f"From {declared.source}."))
        out.append("\n")

    out.append(
        _py_enum(
            "CredentialScope",
            [SCOPE_MACHINE_NAMES[label] for label in vocab.scopes],
            "Credential scopes. The wire carries these; the console shows SCOPE_LABELS.",
        )
    )
    out.append("\n")
    out.append(
        _py_enum(
            "PlatformPermission",
            [PERM_MACHINE_NAMES[label] for label in vocab.perms],
            "The five independently grantable platform permissions.",
        )
    )
    out.append("\n")

    out.append("#: Ordered training stages — drives the console's stage rail.")
    out.append("JOB_STAGES: tuple[JobState, ...] = (")
    for stage in vocab.job_stages:
        member = re.sub(r"\W", "_", stage).upper()
        out.append(f"    JobState.{member},")
    out.append(")")
    out.append("\n")

    out.append("#: Badge tone per value, per group. The console renders these; an")
    out.append("#: unknown value falls back to an untoned badge.")
    out.append("BADGE_TONES: dict[str, dict[str, str]] = {")
    for group, tones in vocab.groups.items():
        out.append(f'    "{group}": {{')
        for value, tone in tones.items():
            out.append(f'        "{value}": "{tone}",')
        out.append("    },")
    out.append("}")
    out.append("\n")

    out.append("#: Machine name -> the label the console displays.")
    out.append("SCOPE_LABELS: dict[CredentialScope, str] = {")
    for label in vocab.scopes:
        member = SCOPE_MACHINE_NAMES[label].replace(":", "_").upper()
        out.append(f'    CredentialScope.{member}: "{label}",')
    out.append("}")
    out.append("")
    out.append("#: Machine name -> the abbreviated label used in table columns.")
    out.append("SCOPE_SHORT_LABELS: dict[CredentialScope, str] = {")
    for label in vocab.scopes:
        member = SCOPE_MACHINE_NAMES[label].replace(":", "_").upper()
        out.append(f'    CredentialScope.{member}: "{vocab.scope_short[label]}",')
    out.append("}")
    out.append("")
    out.append("PERMISSION_LABELS: dict[PlatformPermission, str] = {")
    for label in vocab.perms:
        out.append(f'    PlatformPermission.{PERM_MACHINE_NAMES[label].upper()}: "{label}",')
    out.append("}")
    out.append("")

    for declared in DECLARED:
        if not declared.labels:
            continue
        class_name = "".join(part.title() for part in declared.name.split("_"))
        out.append(f"{declared.name.upper()}_LABELS: dict[{class_name}, str] = {{")
        for value in declared.values:
            member = re.sub(r"\W", "_", value).upper()
            out.append(f'    {class_name}.{member}: "{declared.labels.get(value, value)}",')
        out.append("}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_typescript(vocab: Vocabulary) -> str:
    out: list[str] = [
        "/**",
        " * Shared vocabulary.",
        " *",
        " * " + BANNER.replace("\n", "\n * "),
        " */",
        "",
    ]

    ts_names = {
        "job": "JobState",
        "model": "ModelVersionStatus",
        "deploy": "DeploymentState",
        "tenant": "TenantStatus",
        "user": "UserStatus",
        "outcome": "AuditOutcome",
        "sev": "Severity",
    }

    def union(name: str, values: list[str]) -> None:
        rendered = "\n  | ".join(f"'{v}'" for v in values)
        out.append(f"export type {name} =\n  | {rendered};")
        out.append("")

    for group, tones in vocab.groups.items():
        union(ts_names.get(group, group), list(tones))

    for declared in DECLARED:
        name = "".join(part.title() for part in declared.name.split("_"))
        union(name, list(declared.values))

    union("CredentialScope", [SCOPE_MACHINE_NAMES[label] for label in vocab.scopes])
    union("PlatformPermission", [PERM_MACHINE_NAMES[label] for label in vocab.perms])

    out.append("export type BadgeTone = 'ok' | 'warn' | 'danger' | 'info' | 'neu';")
    out.append("")
    out.append("/** Ordered training stages — drives the stage rail. */")
    stages = ", ".join(f"'{s}'" for s in vocab.job_stages)
    out.append(f"export const JOB_STAGES = [{stages}] as const;")
    out.append("")
    out.append("/** Badge tone per value, per group. `Badge` looks the tone up here")
    out.append(" *  rather than hard-coding a colour per value. */")
    out.append("export const BADGE_TONES: Record<string, Record<string, BadgeTone>> = {")
    for group, tones in vocab.groups.items():
        pairs = ", ".join(f"{value}: '{tone}'" for value, tone in tones.items())
        out.append(f"  {group}: {{ {pairs} }},")
    out.append("};")
    out.append("")
    out.append("export const SCOPE_LABELS: Record<CredentialScope, string> = {")
    for label in vocab.scopes:
        out.append(f"  '{SCOPE_MACHINE_NAMES[label]}': '{label}',")
    out.append("};")
    out.append("")
    out.append("export const SCOPE_SHORT_LABELS: Record<CredentialScope, string> = {")
    for label in vocab.scopes:
        out.append(f"  '{SCOPE_MACHINE_NAMES[label]}': '{vocab.scope_short[label]}',")
    out.append("};")
    out.append("")
    out.append("export const PERMISSION_LABELS: Record<PlatformPermission, string> = {")
    for label in vocab.perms:
        out.append(f"  '{PERM_MACHINE_NAMES[label]}': '{label}',")
    out.append("};")
    out.append("")

    for declared in DECLARED:
        if not declared.labels:
            continue
        name = "".join(part.title() for part in declared.name.split("_"))
        out.append(f"export const {declared.name.upper()}_LABELS: Record<{name}, string> = {{")
        for value in declared.values:
            out.append(f"  '{value}': '{declared.labels.get(value, value)}',")
        out.append("};")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- main


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated files are stale rather than rewriting them",
    )
    args = parser.parse_args()

    vocab = load_vocabulary()
    outputs = {PYTHON_OUT: render_python(vocab), TYPESCRIPT_OUT: render_typescript(vocab)}

    stale: list[Path] = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        print(
            "generated vocabulary is stale:\n  - "
            + "\n  - ".join(str(p.relative_to(ROOT)) for p in stale)
            + "\n\nRun `python scripts/gen_enums.py` and commit the result.",
            file=sys.stderr,
        )
        return 1

    if not args.check:
        total = sum(len(v) for v in vocab.groups.values())
        print(
            f"{len(vocab.groups)} badge groups ({total} values), "
            f"{len(vocab.job_stages)} stages, {len(vocab.scopes)} scopes, "
            f"{len(vocab.perms)} permissions, {len(DECLARED)} declared vocabularies"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
