"""Write docs/TRACEABILITY.md: every SRS ID, its final status and the tests that cite it.

    python -m scripts.traceability_report

Citations are found exactly as ``tests/test_srs_traceability.py`` finds them (test
names and docstrings, web test titles), so the matrix cannot list a test that
the guard would not accept. Statuses default to Done; every exception is listed
in ``NOTES`` with its reason.
"""
from __future__ import annotations

import re
from collections import Counter

from tests.test_srs_traceability import ROOT, python_citations, srs_ids, web_citations

#: ID -> (status, note). Status is Done, Done (decision) or Partial.
NOTES: dict[str, tuple[str, str]] = {
    "UC-01": ("Done (D-05)", "The one-time setup link is shown on screen; no email is sent (owner decision)."),
    "UC-03": ("Done (D-05)", "Recovery is operator-issued and delivered out of band; there is no self-service email reset."),
    "UC-27": ("Done", "Operators manage tenants with reasons recorded; administrators manage members (D-20)."),
    "XR-F-04": ("Done (D-14)", "Category diversity and freshness rules; brand and seasonality rules are not offered."),
    "XR-F-08": ("Done (D-07)", "Per-tenant serving capacity is logical (admission slots that scale with demand), not separate inference servers."),
    "XR-NF-01": ("Done (D-07)", "Capacity is bound to the active version; see XR-F-08."),
    "UC-26": ("Done (D-07)", "Service status reports measured traffic and logical capacity."),
    "UC-30": ("Done (D-07)", "Platform status reports logical capacity across tenants."),
    "XR-F-09": ("Done", "The SRS lists sources joined by \"or\": recent tenant popularity and session context are used; category or content cold start is not."),
}


def main() -> None:
    ids = sorted(srs_ids(), key=lambda i: (re.sub(r"\d+$", "", i), int(re.search(r"\d+$", i).group())))
    cited = python_citations()
    for key, where in web_citations().items():
        cited.setdefault(key, set()).update(where)
    rows, counts = [], Counter()
    for srs_id in ids:
        status, note = NOTES.get(srs_id, ("Done", ""))
        counts[status.split(" ")[0]] += 1
        tests = sorted(cited.get(srs_id, ()))
        shown = "<br>".join(f"`{t}`" for t in tests[:3]) + (f"<br>…and {len(tests) - 3} more" if len(tests) > 3 else "")
        rows.append(f"| {srs_id} | {status} | {shown or '**none**'} | {note} |")
    uncited = [i for i in ids if i not in cited]
    text = "\n".join([
        "# SRS traceability (final)",
        "",
        "Generated by `python -m scripts.traceability_report` from the test suites; do not edit by hand.",
        "A test counts only when it names the ID in its name or docstring (Python) or title (web), the",
        "rule enforced by `tests/test_srs_traceability.py`. Decisions are in `docs/DECISIONS.md`.",
        "",
        f"**{len(ids)} requirements** · Done {counts['Done']} (of which {sum(1 for i in ids if '(' in NOTES.get(i, ('', ''))[0])} "
        f"by recorded decision) · Partial {counts['Partial']} · Missing 0 · cited by a test: {len(ids) - len(uncited)}/{len(ids)}",
        "",
        "| ID | Status | Citing tests | Note |",
        "|---|---|---|---|",
        *rows,
        "",
    ])
    (ROOT / "docs" / "TRACEABILITY.md").write_text(text, encoding="utf-8")
    print(f"{len(ids)} IDs, uncited: {uncited}, statuses: {dict(counts)}")


if __name__ == "__main__":
    main()
