/**
 * Shared vocabulary.
 *
 * GENERATED by scripts/gen_enums.py from "Design system decision pending/GraphRec Console.dc.html".
 * Do not edit by hand. Run `python scripts/gen_enums.py` after changing the prototype.
 */

export type JobState =
  | 'queued'
  | 'waiting_for_resources'
  | 'preparing_data'
  | 'building_graph'
  | 'training'
  | 'evaluating'
  | 'indexing_embeddings'
  | 'registering'
  | 'cancelling'
  | 'cancelled'
  | 'failed'
  | 'succeeded';

export type ModelVersionStatus =
  | 'registered'
  | 'archived'
  | 'eligible'
  | 'retired'
  | 'rejected'
  | 'failed_deployment'
  | 'active';

export type DeploymentState =
  | 'stopped'
  | 'pending'
  | 'progressing'
  | 'degraded'
  | 'rolling_back'
  | 'available';

export type TenantStatus =
  | 'deleted'
  | 'pending'
  | 'suspended'
  | 'deleting'
  | 'active';

export type UserStatus =
  | 'invited'
  | 'locked'
  | 'disabled'
  | 'active';

export type AuditOutcome =
  | 'cancelled'
  | 'denied'
  | 'failed'
  | 'succeeded';

export type Severity =
  | 'info'
  | 'warning'
  | 'error'
  | 'critical';

export type credential =
  | 'usable'
  | 'expired'
  | 'revoked';

export type submission =
  | 'processing'
  | 'succeeded'
  | 'failed';

export type Availability =
  | 'in_stock'
  | 'low_stock'
  | 'out_of_stock';

export type EventType =
  | 'view'
  | 'add_to_cart'
  | 'purchase'
  | 'remove_from_cart';

export type SubmissionKind =
  | 'product_sync'
  | 'event_batch';

export type SubmissionStatus =
  | 'received'
  | 'validating'
  | 'applying'
  | 'completed'
  | 'failed';

export type UsageType =
  | 'events'
  | 'recommendations'
  | 'training'
  | 'products'
  | 'storage'
  | 'service_capacity';

export type MeasurementStatus =
  | 'measured'
  | 'delayed'
  | 'unavailable';

export type AuditActor =
  | 'tenant_user'
  | 'tenant_application'
  | 'system_process'
  | 'platform_administrator';

export type AuditAction =
  | 'credential'
  | 'training'
  | 'activation'
  | 'rollback'
  | 'quota'
  | 'tenant'
  | 'access'
  | 'security';

export type FailureArea =
  | 'serving'
  | 'ingestion'
  | 'training'
  | 'activation'
  | 'capacity';

export type CredentialState =
  | 'usable'
  | 'expired'
  | 'revoked';

export type TenantRole =
  | 'tenant_administrator'
  | 'tenant_developer';

export type CredentialScope =
  | 'catalog:write'
  | 'events:write'
  | 'recommendations:read'
  | 'feedback:write'
  | 'submissions:read';

export type PlatformPermission =
  | 'platform'
  | 'plan_management'
  | 'platform_scope'
  | 'monitoring'
  | 'audit';

export type BadgeTone = 'ok' | 'warn' | 'danger' | 'info' | 'neu';

/** Ordered training stages — drives the stage rail. */
export const JOB_STAGES = ['queued', 'waiting_for_resources', 'preparing_data', 'building_graph', 'training', 'evaluating', 'indexing_embeddings', 'registering', 'succeeded'] as const;

/** Badge tone per value, per group. `Badge` looks the tone up here
 *  rather than hard-coding a colour per value. */
export const BADGE_TONES: Record<string, Record<string, BadgeTone>> = {
  job: { queued: 'neu', waiting_for_resources: 'neu', preparing_data: 'info', building_graph: 'info', training: 'info', evaluating: 'info', indexing_embeddings: 'info', registering: 'info', cancelling: 'warn', cancelled: 'warn', failed: 'danger', succeeded: 'ok' },
  model: { registered: 'neu', archived: 'neu', eligible: 'info', retired: 'warn', rejected: 'warn', failed_deployment: 'danger', active: 'ok' },
  deploy: { stopped: 'neu', pending: 'info', progressing: 'info', degraded: 'warn', rolling_back: 'warn', available: 'ok' },
  tenant: { deleted: 'neu', pending: 'info', suspended: 'warn', deleting: 'warn', active: 'ok' },
  user: { invited: 'info', locked: 'warn', disabled: 'danger', active: 'ok' },
  outcome: { cancelled: 'neu', denied: 'warn', failed: 'danger', succeeded: 'ok' },
  sev: { info: 'info', warning: 'warn', error: 'danger', critical: 'danger' },
  credential: { usable: 'ok', expired: 'warn', revoked: 'danger' },
  submission: { processing: 'info', succeeded: 'ok', failed: 'danger' },
};

export const SCOPE_LABELS: Record<CredentialScope, string> = {
  'catalog:write': 'catalog write & synchronization',
  'events:write': 'event submission (single and batch)',
  'recommendations:read': 'recommendation requests',
  'feedback:write': 'recommendation feedback',
  'submissions:read': 'submission result read',
};

export const SCOPE_SHORT_LABELS: Record<CredentialScope, string> = {
  'catalog:write': 'catalog write',
  'events:write': 'event submission',
  'recommendations:read': 'recommendations',
  'feedback:write': 'feedback',
  'submissions:read': 'result read',
};

export const PERMISSION_LABELS: Record<PlatformPermission, string> = {
  'platform': 'platform permission',
  'plan_management': 'plan-management permission',
  'platform_scope': 'authorized platform scope',
  'monitoring': 'monitoring access',
  'audit': 'audit permission',
};

export const SUBMISSION_KIND_LABELS: Record<SubmissionKind, string> = {
  'product_sync': 'product sync',
  'event_batch': 'event batch',
};

export const MEASUREMENT_STATUS_LABELS: Record<MeasurementStatus, string> = {
  'measured': 'measured',
  'delayed': 'measurement delayed',
  'unavailable': 'unavailable',
};

export const TENANT_ROLE_LABELS: Record<TenantRole, string> = {
  'tenant_administrator': 'tenant administrator',
  'tenant_developer': 'tenant developer',
};
